image: "python:3.5"

before_script:
  - python --version

stages:
  - mlb_refresh
  - nhl_refresh
  - nfl_refresh

sabr:
  stage: mlb_refresh
  tags:
    - gitlab-org
  script:
    - pip install -r requirements.txt
    - cd projects/SABR
    - python refresh.py

corsica:
  stage: nhl_refresh
  tags:
    - gitlab-org
  script:
    - pip install -r requirements.txt
    - cd projects/Corsica
    - python refresh.py

wopr:
  stage: nfl_refresh
  tags:
    - gitlab-org
  script:
    - pip install -r requirements.txt
    - cd projects/WOPR
    - python refresh.py