image: "python:3.5"

services:
  - mongo:latest

before_script:
  - python --version

stages:
  - mlb_refresh
  - nhl_refresh
  - nfl_refresh

sabr:
  stage: mlb_refresh
  tags:
    - gitlab-org
  script:
    - pip install -r requirements.txt
    - python projects/SABR/refresh.py

corsica:
  stage: nhl_refresh
  tags:
    - gitlab-org
  script:
    - python projects/Corsica/refresh.py

wopr:
  stage: nfl_refresh
  tags:
    - gitlab-org
  script:
    - python projects/WOPR/refresh.py